language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
before_script:
  - dotnet restore
script:
  - msbuild /p:Configuration=Release WebApplication1.sln
  - dotnet test ./WebApplication1Tests -c Debug -f netcoreapp2.1