language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
before_script:
  - dotnet restore
script:
  - dotnet build ./WebApplication1Tests -c Debug -f netcoreapp2.1	
  - dotnet test ./WebApplication1Tests -c Debug -f netcoreapp2.1
